/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#5e4200",
        "on-surface": "#1c1b1b",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#271900",
        "secondary-fixed": "#ffdea8",
        "inverse-surface": "#313030",
        "on-primary-fixed-variant": "#7f2b00",
        "surface-bright": "#fcf9f8",
        "primary-fixed": "#ffdbce",
        "tertiary-fixed": "#72fe88",
        "inverse-primary": "#ffb599",
        "primary-container": "#f26522",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#1c1b1b",
        "primary-fixed-dim": "#ffb599",
        "tertiary": "#006e28",
        "error": "#ba1a1a",
        "surface-variant": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00a841",
        "on-tertiary-fixed": "#002107",
        "on-surface-variant": "#594138",
        "outline": "#8d7166",
        "surface-container-highest": "#e5e2e1",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed": "#370e00",
        "surface-tint": "#a63b00",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9d9",
        "secondary-container": "#feb700",
        "on-tertiary-container": "#00320e",
        "surface": "#fcf9f8",
        "secondary-fixed-dim": "#ffba20",
        "background": "#fcf9f8",
        "on-secondary": "#ffffff",
        "surface-container-high": "#eae7e7",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#00531c",
        "on-primary-container": "#4f1800",
        "outline-variant": "#e1bfb3",
        "on-secondary-container": "#6b4b00",
        "tertiary-fixed-dim": "#53e16f",
        "primary": "#a63b00",
        "surface-container": "#f0eded",
        "secondary": "#7c5800"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        sm: "8px",
        xl: "48px",
        gutter: "16px",
        md: "16px",
        xs: "4px",
        "container-max": "1200px",
        base: "8px",
        lg: "24px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-price": ["Inter", "sans-serif"],
        "price-card": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-price": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "price-card": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
