import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.*;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.text.SimpleDateFormat;

public class TestVNPay {
    public static void main(String[] args) throws Exception {
        String vnp_HashSecret = "SWTQ3QEHJTK5C1S8Z4FAM9MS9GG9MGVG";
        String vnp_Url = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html";
        
        Map<String, String> vnp_Params = new HashMap<>();
        vnp_Params.put("vnp_Version", "2.1.0");
        vnp_Params.put("vnp_Command", "pay");
        vnp_Params.put("vnp_TmnCode", "U1JI07HL");
        vnp_Params.put("vnp_Amount", "99900000");
        vnp_Params.put("vnp_CurrCode", "VND");
        vnp_Params.put("vnp_TxnRef", "12345678_1");
        vnp_Params.put("vnp_OrderInfo", "MuaGoi_PRO_1");
        vnp_Params.put("vnp_OrderType", "other");
        vnp_Params.put("vnp_Locale", "vn");
        vnp_Params.put("vnp_ReturnUrl", "http://localhost:5173/payment-return");
        vnp_Params.put("vnp_IpAddr", "127.0.0.1");
        
        Calendar cld = Calendar.getInstance(TimeZone.getTimeZone("Asia/Ho_Chi_Minh"));
        SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMddHHmmss");
        String vnp_CreateDate = formatter.format(cld.getTime());
        vnp_Params.put("vnp_CreateDate", vnp_CreateDate);
        
        cld.add(Calendar.MINUTE, 15);
        String vnp_ExpireDate = formatter.format(cld.getTime());
        vnp_Params.put("vnp_ExpireDate", vnp_ExpireDate);

        List<String> fieldNames = new ArrayList<>(vnp_Params.keySet());
        Collections.sort(fieldNames);
        
        StringBuilder hashData = new StringBuilder();
        StringBuilder query = new StringBuilder();
        Iterator<String> itr = fieldNames.iterator();
        while (itr.hasNext()) {
            String fieldName = (String) itr.next();
            String fieldValue = (String) vnp_Params.get(fieldName);
            if ((fieldValue != null) && (fieldValue.length() > 0)) {
                // Build hash data
                hashData.append(fieldName);
                hashData.append('=');
                hashData.append(URLEncoder.encode(fieldValue, StandardCharsets.US_ASCII.toString()));
                // Build query
                query.append(URLEncoder.encode(fieldName, StandardCharsets.US_ASCII.toString()));
                query.append('=');
                query.append(URLEncoder.encode(fieldValue, StandardCharsets.US_ASCII.toString()));
                if (itr.hasNext()) {
                    query.append('&');
                    hashData.append('&');
                }
            }
        }
        String queryUrl = query.toString();
        String vnp_SecureHash = hmacSHA512(vnp_HashSecret, hashData.toString());
        queryUrl += "&vnp_SecureHash=" + vnp_SecureHash;
        String paymentUrl = vnp_Url + "?" + queryUrl;
        
        System.out.println("\n==== VNPAY URL GENERATED BY OFFICIAL SDK FORMAT ====");
        System.out.println(paymentUrl);
        System.out.println("===================================================\n");
        
        // NOW USING MY CUSTOM FORMAT
        StringBuilder hashData2 = new StringBuilder();
        StringBuilder query2 = new StringBuilder();
        boolean first = true;
        for (String fieldName : fieldNames) {
            String fieldValue = vnp_Params.get(fieldName);
            if (fieldValue != null && fieldValue.length() > 0) {
                if (!first) {
                    hashData2.append('&');
                    query2.append('&');
                }
                String encodedValue = URLEncoder.encode(fieldValue, StandardCharsets.UTF_8.toString())
                        .replace("+", "%20")
                        .replace("*", "%2A")
                        .replace("%7E", "~");
                        
                hashData2.append(fieldName).append('=').append(encodedValue);
                query2.append(URLEncoder.encode(fieldName, StandardCharsets.UTF_8.toString())).append('=').append(encodedValue);
                first = false;
            }
        }
        
        String queryUrl2 = query2.toString();
        String vnp_SecureHash2 = hmacSHA512(vnp_HashSecret, hashData2.toString());
        queryUrl2 += "&vnp_SecureHash=" + vnp_SecureHash2;
        String paymentUrl2 = vnp_Url + "?" + queryUrl2;
        
        System.out.println("==== VNPAY URL GENERATED BY MY FORMAT ====");
        System.out.println(paymentUrl2);
        System.out.println("===================================================\n");
        
        if (paymentUrl.equals(paymentUrl2)) {
            System.out.println("RESULT: MATCH! Both formats generate the same URL!");
        } else {
            System.out.println("RESULT: MISMATCH!");
            System.out.println("HashData1: " + hashData.toString());
            System.out.println("HashData2: " + hashData2.toString());
        }
    }
    
    public static String hmacSHA512(final String key, final String data) {
        try {
            Mac hmac512 = Mac.getInstance("HmacSHA512");
            byte[] hmacKeyBytes = key.getBytes(StandardCharsets.UTF_8);
            SecretKeySpec secretKey = new SecretKeySpec(hmacKeyBytes, "HmacSHA512");
            hmac512.init(secretKey);
            byte[] dataBytes = data.getBytes(StandardCharsets.UTF_8);
            byte[] result = hmac512.doFinal(dataBytes);
            StringBuilder sb = new StringBuilder(2 * result.length);
            for (byte b : result) {
                sb.append(String.format("%02x", b & 0xff));
            }
            return sb.toString();
        } catch(Exception e) {
            return "";
        }
    }
}
