# Đặt cổng chạy cố định cho Eureka Server luôn là 8761
server.port=8761
spring.application.name=eureka-server

# Báo cho ứng dụng biết nó là máy chủ, không cần tự đăng ký chính nó vào danh bạ
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false