spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_db
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
